### ISSUE TITLE
faucet down?

### ISSUE THREAD

**Issue by robertkowalski** [sebs/ethrain#3]
I get an error from the API:

```
$ ./bin/ethrain 107a876b283815ba899294f50392b46e22d76f43
{ Error: connect ECONNREFUSED 198.199.82.46:443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '198.199.82.46',
  port: 443 } undefined
```

**Comment by sebs** [comment]
yes, looks like
